### ISSUE TITLE
L'opérateur ++ s'effectue trop tôt

### ISSUE THREAD

**Issue by GuillaumeGas** [GNU-Ymir/gymir#13]
Généralement, dans le cas d'un affectation par exemple, on réalise d'abord l'affectation puis le ++. Exemple : 
```C++
let a = 0, b = 1;
for (i in 0U .. 10U)
    a = b++; // on doit d'abord faire a = b, puis b++;
```
Tu comptes reproduire ce comportement ? Et introduire le ++var par exemple ?

**Comment by EmileCadorel** [comment]
Noooooon.
Pourquoi tu t'obstinne à vouloir que les truc de merde du C existent en Ymir ?^^

**Comment by GuillaumeGas** [comment]
ça m'a obligé à écrire une ligne en plus :(
