### ISSUE TITLE
Possible erreur avec l'itération sur un range

### ISSUE THREAD

**Issue by GuillaumeGas** [GNU-Ymir/gymir#19]
Si on a un range 1 .. 3, ça représente bien 3 valeurs ? 1 et 3 étant tous les deux inclus ?
Si oui, comme le montre le code suivant, la seconde borne est exclue : 

```C++
import core.io;

def main () {
    // rng is r!(int);
    let rng = 1 .. 3;

    for i in rng
        println (i);
}
```

**Comment by EmileCadorel** [comment]
c'est inclue .. exclue.
C'est normal, c'est pour que les accés au tableau soit logique
```Rust

for it in 0U .. array.len {
