### ISSUE TITLE
Erreur affichage des floats

### ISSUE THREAD

**Issue by GuillaumeGas** [GNU-Ymir/gymir#21]
J'ai toujours 0 quand je veux afficher des floats.
J'ai modifié la core pour vérifier que je passais bien dans la bonne fonction de print, et c'est le cas (si je met %d j'ai une valeur de merde). J'ai testé %f au lieux de %lf, rien à faire, toujours 0, c'est bien le bon format pourtant d'après la doc...

Le code de test : 
```C++
import core.io;

// A structure with two fields
struct Point {
    x : float,
    y : float
}

// Struct can be field of another struct
struct
| a : Point
| b : Point
 -> Rectangle;

def printRect (ref rect : Rectangle)
{
    println (rect.a.x, ", ", rect.a.y);
    println (rect.b.x, ", ", rect.b.y);
}

def main () {
    // all values are needed
    let point = Point { .1f, .7f };
    println (point);
    println (point.x);

    let a = .7f;
    println (a);
    
    // A struct can be constructed without value either
    // All fields are set two 0x0.
    let point2 = Point::init; 

    // We can get a tuple from a structure
    // let (x, y) = point.tupleof;

    let rect = Rectangle { point, Point {3.3f, 4.5f } };

    // Structure are printable.
    println (rect);
    printRect (rect);
}

```

**Comment by EmileCadorel** [comment]
oui je sais, mais la raison m'échappe, si j'affiche le code que je génère la valeur est bonne pourtant.
Le plus bizarre c'est que les double eux ils fonctionnent

**Comment by EmileCadorel** [comment]
Ça venait de printf, qui est une fonction C variadic.
En C, il y a un système de promotion des types :
- float -> double
- char, bool, short -> int

Du coup c'est ajouté
