### ISSUE TITLE
Prendre en compte le caractère d'échappement

### ISSUE THREAD

**Issue by JusMultifruits** [GNU-Ymir/gymir#58]
Lors de la création d'un tableau de caractères, on ne peut pas créer le caractère '\0'

**Comment by EmileCadorel** [comment]
on it

**Comment by EmileCadorel** [comment]
Done, il y a les escape char standards : 
```
\a, \b, \f, \n, \r, \t, \v, \\, \', \", \?
```
et les char unicode : 
```
\u{code}
``` 

Donc pour avoir `\0`, il faut faire : `\u{0}`
