### ISSUE TITLE
Permettre de déclarer des variables en extern (C)

### ISSUE THREAD

**Issue by GuillaumeGas** [GNU-Ymir/gymir#6]
Ca peut permettre par exemple d'avoir accès à la variable globale d'erreur `errno`.

**Comment by EmileCadorel** [comment]
depuis la dernière version, :
```
extern errno : int;
static v1 : int;
static v2 = 12;

def main () {
    println (v1); // 0
    println (v2); // 12
    println (errno); 
}
```

**Comment by EmileCadorel** [comment]
bon par contre en fait errno ça marche pas parcequ'il est déclaré bizarrement dans les fichier système
