### ISSUE TITLE
Assert : dynamic cast failed : nullptr

### ISSUE THREAD

**Issue by GuillaumeGas** [GNU-Ymir/gymir#60]
J'ai tenté quelques trucs avec les classes, j'ajoute les fichiers au ticket.
La hiérarchie est la suivante : 
main.yr
geo/
  Point.yr

```
mod main

import std::io
import geo::Point

def main() {
    println("Hello !");

    let p = Point::new();
    println(p._x);
}
```

```
mod geo::Point

pub class Point {
    pub let _x;
    pub let _y;

    self() with self(0, 0) {}
    self(x : i32, y : i32) with _x = x, _y = y {}
}
```

**Comment by EmileCadorel** [comment]
Ok, the problem is that I let the declaration of the attributes pass even if they don't have any type. 
I am on it
